[project]
name = "30daysofai-challenge-in-public"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "apify-client",
    "beautifulsoup4",
    "chromadb",
    "crewai[tools]",
    "langchain",
    "langchain-community",
    "langchain-core",
    "langchain-groq",
    "langgraph",
    "pandas",
    "pypdf2",
    "python-dotenv",
    "requests",
    "sentence-transformers",
    "streamlit",
    "autogluon.tabular",
    "fastapi",
    "uvicorn",
    "pydantic",
]

[tool.pyright]
extraPaths = ["DAY-5"]
